// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbhQjc_nnu4pBgUYdB1ZQ-yICpDwUswW4',
    appId: '1:812782780339:web:d6ecd3c01390615a4015c6',
    messagingSenderId: '812782780339',
    projectId: 'mszbowling',
    authDomain: 'mszbowling.firebaseapp.com',
    databaseURL: 'https://mszbowling.firebaseio.com',
    storageBucket: 'mszbowling.appspot.com',
    measurementId: 'G-JTYF0BSFTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2-UmC4lV1spYX2FirTFshsMgL4tjHpXM',
    appId: '1:812782780339:android:fc60f13e3f792de14015c6',
    messagingSenderId: '812782780339',
    projectId: 'mszbowling',
    databaseURL: 'https://mszbowling.firebaseio.com',
    storageBucket: 'mszbowling.appspot.com',
  );
}
